// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/api/controller/v1/rating/rating_controller.go

// Package rating is a generated GoMock package.
package rating

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIRatingController is a mock of IRatingController interface.
type MockIRatingController struct {
	ctrl     *gomock.Controller
	recorder *MockIRatingControllerMockRecorder
}

// MockIRatingControllerMockRecorder is the mock recorder for MockIRatingController.
type MockIRatingControllerMockRecorder struct {
	mock *MockIRatingController
}

// NewMockIRatingController creates a new mock instance.
func NewMockIRatingController(ctrl *gomock.Controller) *MockIRatingController {
	mock := &MockIRatingController{ctrl: ctrl}
	mock.recorder = &MockIRatingControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRatingController) EXPECT() *MockIRatingControllerMockRecorder {
	return m.recorder
}

// AddRating mocks base method.
func (m *MockIRatingController) AddRating(context *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRating", context)
}

// AddRating indicates an expected call of AddRating.
func (mr *MockIRatingControllerMockRecorder) AddRating(context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRating", reflect.TypeOf((*MockIRatingController)(nil).AddRating), context)
}

// GetAverageRating mocks base method.
func (m *MockIRatingController) GetAverageRating(context *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAverageRating", context)
}

// GetAverageRating indicates an expected call of GetAverageRating.
func (mr *MockIRatingControllerMockRecorder) GetAverageRating(context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRating", reflect.TypeOf((*MockIRatingController)(nil).GetAverageRating), context)
}

// RegisterRoutes mocks base method.
func (m *MockIRatingController) RegisterRoutes(routerGroup *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", routerGroup)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockIRatingControllerMockRecorder) RegisterRoutes(routerGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockIRatingController)(nil).RegisterRoutes), routerGroup)
}
