version: "3.8"

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/db_tables_up.sql:/docker-entrypoint-initdb.d/db_tables_up.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"

  rating-api-app:
    container_name: rating-api
    build: .
    image: rating-api:latest
    ports:
      - "8080:8080"
    environment:
      APP_ENVIRONMENT: "Prev"
      APP_HOST: "localhost:8080"
      POSTGRESQL_CONNECTION_STRING: "postgres://postgres:123456@postgres:5432/postgres?sslmode=disable"
    depends_on:
      - postgres
  
volumes:
  postgres:
    driver: local